In [3]:
import numpy as np
# 用列表去创建
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [4]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr.shape)

(2, 3)


In [12]:
# 内置函数创建
arr = np.zeros((2, 3))
print(arr)
arr = np.ones((2, 3), dtype=np.int32)
print(arr)
arr = np.full((2, 3), 666)
print(arr)
arr = np.diag([1, 2, 3, 4])
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1 1 1]
 [1 1 1]]
[[666 666 666]
 [666 666 666]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [19]:
# 序列创建
arr = np.arange(0, 10, 2)
print(arr)
arr = np.arange(0, 10)
print(arr)
arr = np.linspace(0, 10, 5)
print(arr)
arr = np.random.rand(2, 3)
print(arr)
arr = np.random.randn(2, 3)
print(arr)

[0 2 4 6 8]
[0 1 2 3 4 5 6 7 8 9]
[ 0.   2.5  5.   7.5 10. ]
[[0.92041423 0.82439065 0.28943056]
 [0.72038565 0.6409731  0.20114832]]
[[-0.39361177 -0.35448347 -2.17547458]
 [-0.41679409 -1.60373395 -0.29906411]]
